### ISSUE TITLE
problems when using Modemobmap

### ISSUE THREAD

**Issue by Mitchell1314** [Synacktiv-contrib/Modmobmap#1]
Hi sir,
      I am trying to use your modmobmap, but i got stuck. When I run "python3 modmobmap.py -s /home/winlab01/platform-tools/", i got the responses as follows:
![2019-02-24 17-27-03](https://user-images.githubusercontent.com/15179223/53297399-6dfc3200-3859-11e9-8632-36b4e650058a.png)
By the way, sdb path is //home/winlab01/platform-tools/. Can you give me some help to handle this? Waiting for your reply, thanks.

**Comment by FlUxIuS** [comment]
Hi,

Can you provide details on your setup? What is the current mobile phone version? 
Did you also retry after rebooting the mobile phone? 

Can you also try by using cached operators' list provided in "operators.json"? This list depends also on your current country, so you'll have to change it in case you're not in France.

This first step is a little buggy when passing AT commands from ADB. For a lot of Samsung devices there is a way to expose AT interface through USBSettings by calling *#0808#. After exposing the AT interface you can call the tool with the "-a" argument.
