### ISSUE TITLE
Can not search 4G

### ISSUE THREAD

**Issue by XiaoliChan** [Synacktiv-contrib/Modmobmap#3]
I can not search any 4G by using this tools，only search 3G and 2G

**Comment by XiaoliChan** [comment]
i think this script dose not support TDD lte，how to fix it？

**Comment by FlUxIuS** [comment]
Hi,

The method `parse4Gcell` probably misses regex to parse the logcat output in `engines/android/samsung/ServiceMode.py`.

If you provide me your logcat output when the baseband is camping on a 4G cell, I can add the right regex to support it for your target. But if you have the motivation, you can also patch the code yourself and do a pull request to integrate your patch to the project :)

Thanks in advance!
